### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sabrinabenas** [sabrinabenas/Object-Video-Annotation#1]
- [x] Add python packages
- [x] Add logfile analysis

**Comment by sabrinabenas** [comment]
- [ ] cortar a los 5 minutos
- [x] agregar el nombre del video al logfile 
- [x] chequear paridad en la lista o cambiar que pasa si no cambia de frama
