### ISSUE TITLE
TODO DLC

### ISSUE THREAD

**Issue by sabrinabenas** [sabrinabenas/Object-Video-Annotation#2]
- [ ] Agregar un false o true si se quiere ver el beh de DLC
- [ ] Si True, seleccionar que bodypart se quiere estudiar (ahora solo ve el bdp 'head')
- [ ] poner barra de máscara sobre el objeto
